name: Publish to test environment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main repository
      uses: actions/checkout@v2
    - name: Checkout the gh-pages folder
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300-preview-015135
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore src/Sotsera.Cdn/Sotsera.Cdn.csproj
    - name: Publish
      run: dotnet publish --configuration Release --no-restore -o ./publish src/Sotsera.Cdn/Sotsera.Cdn.csproj
    - name: Update the published assets for this environment
      run: | 
        mkdir -p gh-pages/blazor/3.2.0-rc1.20223.4-v2
        rm -rf gh-pages/blazor/3.2.0-rc1.20223.4-v2
        cp -r publish/wwwroot/_framework/wasm gh-pages/blazor/3.2.0-rc1.20223.4-v2
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GIT_CONFIG_EMAIL: ghidello@users.noreply.github.com
        CLEAN: true
        BRANCH: gh-pages
        FOLDER: gh-pages
